### ISSUE TITLE
Websockets not properly installed with package

### ISSUE THREAD

**Issue by Ben-Brady** [Sheppsu/osu.py#1]
When attempting to import the package I get an error about missing modules

> ModuleNotFoundError: No module named 'websockets'

Installing websockets manually fixes the issue, so I think it's problem with your package not correctly including websockets in the requirements. It's in the requirements.txt, but not in the install_requires I think adding it there would fix the issue.

**Comment by Sheppsu** [comment]
Ok thanks for pointing this out. It should be working now, that is if you download from the github. It won't work for regular pip installation until I push a new version out. You can use `pip install git+https://github.com/Sheepposu/osu.py.git` to download straight from the github
