### ISSUE TITLE
Check if ruleset is in statistics_rulesets field

### ISSUE THREAD

**Issue by descensiontohell** [Sheppsu/osu.py#3]
Attempting to get own data (`api/v2/me`) with OAuth authorization code leads to KeyError if the requested player never played one of the game modes because they don't have the according field in `statistics_rulesets` field (picture)
![image](https://user-images.githubusercontent.com/64037726/177625764-2d7340d8-c488-43cd-81c7-ca4ae09e32e3.png)
![image](https://user-images.githubusercontent.com/64037726/177625867-5022b782-f5ce-4717-a232-97c1465fe4d4.png)
There needs to be a check which of the rulesets present in `statistics_rulesets` field
```
    def __init__(self, data):
        self.osu = UserStatistics(data['osu'])
        self.taiko = UserStatistics(data['taiko']) 
        self.fruits = UserStatistics(data['fruits'])
        self.mania = UserStatistics(data['mania']) 
```
Works perfectly fine with players who have all the game modes in there

**Comment by Sheppsu** [comment]
Solved with #4
